// create actions to start training
export default {
  ROUTINES_LOAD_ACTION: 'ROUTINES_LOAD_ACTION',
  ROUTINES_LOAD_START: 'ROUTINES_LOAD_START',
  ROUTINES_LOAD_SUCCESS: 'ROUTINES_LOAD_SUCCESS',
  ROUTINES_LOAD_FAIL: 'ROUTINES_LOAD_FAIL',

  ROUTINE_ADD_ACTION: 'ROUTINES_ADD_ACTION',
  ROUTINE_ADD_START: 'ROUTINE_ADD_START',
  ROUTINE_ADD_SUCCESS: 'ROUTINE_ADD_SUCCESS',
  ROUTINE_ADD_FAIL: 'ROUTINE_ADD_FAIL',

  ROUTINE_REMOVE_ACTION: 'ROUTINES_REMOVE_ACTION',
  ROUTINE_REMOVE_START: 'ROUTINE_REMOVE_START',
  ROUTINE_REMOVE_SUCCESS: 'ROUTINE_REMOVE_SUCCESS',
  ROUTINE_REMOVE_FAIL: 'ROUTINE_REMOVE_FAIL',

  ROUTINE_CREATE_LIST_ACTION: 'ROUTINE_CREATE_LIST_ACTION',
  ROUTINE_CREATE_LIST_START: 'ROUTINE_CREATE_LIST_START',
  ROUTINE_CREATE_LIST_SUCCESS: 'ROUTINE_CREATE_LIST_SUCCESS',
  ROUTINE_CREATE_LIST_FAIL: 'ROUTINE_CREATE_LIST_FAIL',

  ROUTINE_CREATE_SAVE_ACTION: 'ROUTINE_SAVE_LIST_ACTION',
  ROUTINE_CREATE_SAVE_START: 'ROUTINE_SAVE_LIST_START',
  ROUTINE_CREATE_SAVE_SUCCESS: 'ROUTINE_SAVE_LIST_SUCCESS',
  ROUTINE_CREATE_SAVE_FAIL: 'ROUTINE_SAVE_LIST_FAIL',

  ROUTINE_CREATE_ADD_ACTION: 'ROUTINE_CREATE_ADD_ACTION',
  ROUTINE_CREATE_ADD_START: 'ROUTINE_CREATE_ADD_START',
  ROUTINE_CREATE_ADD_SUCCESS: 'ROUTINE_CREATE_ADD_SUCCESS',
  ROUTINE_CREATE_ADD_FAIL: 'ROUTINE_CREATE_ADD_FAIL',

  ROUTINE_CREATE_REMOVE_ACTION: 'ROUTINE_CREATE_REMOVE_ACTION',
  ROUTINE_CREATE_REMOVE_START: 'ROUTINE_CREATE_REMOVE_START',
  ROUTINE_CREATE_REMOVE_SUCCESS: 'ROUTINE_CREATE_REMOVE_SUCCESS',
  ROUTINE_CREATE_REMOVE_FAIL: 'ROUTINE_CREATE_REMOVE_FAIL',

  ROUTINE_CHOOSE_ACTIVE: 'ROUTINE_CHOOSE_ACTIVE',

  BODY_DATA_LOAD_ACTION: 'BODY_DATA_LOAD_ACTION',
  BODY_DATA_LOAD_START: 'BODY_DATA_LOAD_START',
  BODY_DATA_LOAD_SUCCESS: 'BODY_DATA_LOAD_SUCCESS',
  BODY_DATA_LOAD_FAIL: 'BODY_DATA_LOAD_FAIL',

  BODY_DATA_ADD_ACTION: 'BODY_DATA_ADD_ACTION',
  BODY_DATA_ADD_START: 'BODY_DATA_ADD_START',
  BODY_DATA_ADD_SUCCESS: 'BODY_DATA_ADD_SUCCESS',
  BODY_DATA_ADD_FAIL: 'BODY_DATA_ADD_FAIL',

  BODY_DATA_UPDATE_ACTION: 'BODY_DATA_UPDATE_ACTION',
  BODY_DATA_UPDATE_START: 'BODY_DATA_UPDATE_START',
  BODY_DATA_UPDATE_SUCCESS: 'BODY_DATA_UPDATE_SUCCESS',
  BODY_DATA_UPDATE_FAIL: 'BODY_DATA_UPDATE_FAIL',

  BODY_DATA_CLICKED_ITEM: 'BODY_DATA_CLICKED_ITEM',

  EXERCISES_LOAD_ACTION: 'EXERCISES_LOAD_ACTION',
  EXERCISES_LOAD_START: 'EXERCISES_LOAD_START',
  EXERCISES_LOAD_SUCCESS: 'EXERCISES_LOAD_SUCCESS',
  EXERCISES_LOAD_FAIL: 'EXERCISES_LOAD_FAIL',

  EXERCISES_REFRESH_ACTION: 'EXERCISES_REFRESH_ACTION',
  EXERCISES_REFRESH_START: 'EXERCISES_REFRESH_START',
  EXERCISES_REFRESH_SUCCESS: 'EXERCISES_REFRESH_SUCCESS',
  EXERCISES_REFRESH_FAIL: 'EXERCISES_REFRESH_FAIL',

  FAVORITE_EXERCISES_LOAD_ACTION: 'FAVORITE_EXERCISES_LOAD_ACTION',
  FAVORITE_EXERCISES_LOAD_START: 'FAVORITE_EXERCISES_LOAD_START',
  FAVORITE_EXERCISES_LOAD_SUCCESS: 'FAVORITE_EXERCISES_LOAD_SUCCESS',
  FAVORITE_EXERCISES_LOAD_FAIL: 'FAVORITE_EXERCISES_LOAD_FAIL',

  FAVORITE_EXERCISES_ADD_ACTION: 'FAVORITE_EXERCISES_ADD_ACTION',
  FAVORITE_EXERCISES_ADD_START: 'FAVORITE_EXERCISES_ADD_START',
  FAVORITE_EXERCISES_ADD_SUCCESS: 'FAVORITE_EXERCISES_ADD_SUCCESS',
  FAVORITE_EXERCISES_ADD_FAIL: 'FAVORITE_EXERCISES_ADD_FAIL',

  FAVORITE_EXERCISES_REMOVE_ACTION: 'FAVORITE_EXERCISES_REMOVE_ACTION',
  FAVORITE_EXERCISES_REMOVE_START: 'FAVORITE_EXERCISES_REMOVE_START',
  FAVORITE_EXERCISES_REMOVE_SUCCESS: 'FAVORITE_EXERCISES_REMOVE_SUCCESS',
  FAVORITE_EXERCISES_REMOVE_FAIL: 'FAVORITE_EXERCISES_REMOVE_FAIL',

  TRAINING_ADD_SERIES_ACTION: 'TRAINING_ADD_SERIES_ACTION',
  TRAINING_ADD_SERIES_START: 'TRAINING_ADD_SERIES_START',
  TRAINING_ADD_SERIES_FAIL: 'TRAINING_ADD_SERIES_FAIL',
  TRAINING_ADD_SERIES_SUCCESS: 'TRAINING_ADD_SERIES_SUCCESS',

  TRAINING_LOAD_ACTION: 'TRAINING_LOAD_ACTION',
  TRAINING_LOAD_START: 'TRAINING_LOAD_START',
  TRAINING_LOAD_SUCCESS: 'TRAINING_LOAD_SUCCESS',
  TRAINING_LOAD_FAIL: 'TRAINING_LOAD_FAIL',

  TRAINING_ADD_ACTION: 'TRAINING_ADD_ACTION',
  TRAINING_ADD_START: 'TRAINING_ADD_START',
  TRAINING_ADD_SUCCESS: 'TRAINING_ADD_SUCCESS',
  TRAINING_ADD_FAIL: 'TRAINING_ADD_FAIL',

  TRAINING_START_ACTION: 'TRAINING_START_ACTION',
  TRAINING_END_ACTION: 'TRAINING_END_ACTION'
}
