export default {
  ROUTINES_LOAD_ACTION: 'ROUTINES_LOAD_ACTION',
  ROUTINES_LOAD_START: 'ROUTINES_LOAD_START',
  ROUTINES_LOAD_SUCCESS: 'ROUTINES_LOAD_SUCCESS',
  ROUTINES_LOAD_FAIL: 'ROUTINES_LOAD_FAIL',

  ROUTINE_ADD_ACTION: 'ROUTINES_ADD_ACTION',
  ROUTINE_ADD_START: 'ROUTINE_ADD_START',
  ROUTINE_ADD_SUCCESS: 'ROUTINE_ADD_SUCCESS',
  ROUTINE_ADD_FAIL: 'ROUTINE_ADD_FAIL',

  ROUTINE_REMOVE_ACTION: 'ROUTINES_REMOVE_ACTION',
  ROUTINE_REMOVE_START: 'ROUTINE_REMOVE_START',
  ROUTINE_REMOVE_SUCCESS: 'ROUTINE_REMOVE_SUCCESS',
  ROUTINE_REMOVE_FAIL: 'ROUTINE_REMOVE_FAIL',

  BODY_DATA_LOAD_ACTION: 'BODY_DATA_LOAD_ACTION',
  BODY_DATA_LOAD_START: 'BODY_DATA_LOAD_START',
  BODY_DATA_LOAD_SUCCESS: 'BODY_DATA_LOAD_SUCCESS',
  BODY_DATA_LOAD_FAIL: 'BODY_DATA_LOAD_FAIL',

  BODY_DATA_ADD_ACTION: 'BODY_DATA_ADD_ACTION',
  BODY_DATA_ADD_START: 'BODY_DATA_ADD_START',
  BODY_DATA_ADD_SUCCESS: 'BODY_DATA_ADD_SUCCESS',
  BODY_DATA_ADD_FAIL: 'BODY_DATA_ADD_FAIL',

  BODY_DATA_UPDATE_ACTION: 'BODY_DATA_UPDATE_ACTION',
  BODY_DATA_UPDATE_START: 'BODY_DATA_UPDATE_START',
  BODY_DATA_UPDATE_SUCCESS: 'BODY_DATA_UPDATE_SUCCESS',
  BODY_DATA_UPDATE_FAIL: 'BODY_DATA_UPDATE_FAIL',

  BODY_DATA_CLICKED_ITEM: 'BODY_DATA_CLICKED_ITEM'
}
